package com.soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T23:28:46.603-07:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.soap.com/", name = "MessageGen")
@XmlSeeAlso({ObjectFactory.class})
public interface MessageGen {

    @WebMethod
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://ws.soap.com/", className = "com.soap.ws.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://ws.soap.com/", className = "com.soap.ws.GetMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getMessage();

    @WebMethod
    @RequestWrapper(localName = "getTotal", targetNamespace = "http://ws.soap.com/", className = "com.soap.ws.GetTotal")
    @ResponseWrapper(localName = "getTotalResponse", targetNamespace = "http://ws.soap.com/", className = "com.soap.ws.GetTotalResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Double getTotal(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
